### ISSUE TITLE
AMD port ToDo: Format AMD port output for energy values, note about energy counters, JSON implementation, documentation 

### ISSUE THREAD

**Issue by tpatki** [LLNL/variorum#224]
- [ ] For the AMD port, we need to change the formatting style of some of the output/print functions (eg print energy functions) to include hostname and other details. We are blocked as no system is available for testing this.

- [ ] There is also a known issue with both sockets reporting the same energy value, but this seems to be an ESMI or HSMP driver issue that we can't debug yet due to lack of steady/privileged access to an AMD node.

- [x] JSON implementation needs to be added. 

- [x] Documentation needs to be updated to explain the underlying specifics of the architecture

**Comment by tpatki** [comment]
Blocked on this due to access issues for v0.8.

**Comment by tpatki** [comment]
@slabasan Maybe we should revisit this and clean up the AMD port's output formatting for v0.9.
